### ISSUE TITLE
Small correction in the readme

### ISSUE THREAD

**Issue by ggnkua** [mrange/pt_src3#1]
Hi there,

First off: many thanks for releasing the player source all these years ago, it was (and still is) a landmark in STE audio! I even used it in a small production back in 2000 or so (https://www.pouet.net/prod.php?which=7872).

I just wanted to give you a heads up since you linked my source repository in your readme.
https://github.com/mrange/pt_src3/blob/b4d91a9e716adc89ba813458e28ecb087930b5df/README.md?plain=1#L627
I had your source code in a folder called "Lance!" but, from what I understand, by the time you already were a member of Impulse. So I thought I'd move the source to an "Impulse" folder instead: https://github.com/ggnkua/Atari_ST_Sources/tree/master/ASM/Impulse/UCDM

So, that's pretty much it. If you think I should move it back as it was, just let me know. I just acted on an impulse (har har) without asking you first.

Again, thanks much for the player and the writeup!
George (GGN)

**Comment by mrange** [comment]
Thank you. I will update the blog. I always appreciate a good pun as well. Good work.

**Comment by mrange** [comment]
I believe this issue is resolved now as I updated the link and added your kind words to the blog.
